build: single multiple mutex cond sema rwlock

single:
	$(CC) -o single.o single.c

multiple:
	$(CC) -o multiple.o multiple.c

mutex:
	$(CC) -o mutex.o mutex.c

cond:
	$(CC) -o cond.o cond.c

sema:
	$(CC) -o sema.o sema.c

rwlock:
	$(CC) -o rwlock.o rwlock.c

clean:
	rm *.o
